# Generated by Django 5.2.5 on 2025-08-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_languages_comment_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='languages',
            new_name='language',
        ),
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
