# Generated by Django 5.2.5 on 2025-08-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_languages_language_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
